name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: simple_bank
        options: >-
          --health_command pg_isready
          --health_interval: 10s
          --health_timeout: 5s
          --health_retries: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
